### ISSUE TITLE
ModuleNotFoundError: No module named 'pymodbus.client.sync'

### ISSUE THREAD

**Issue by jvrrr** [nmakel/solaredge_modbus#62]
Hi,

I tried to run the example file but get a error. 
Do I something wrong or is there something I need to install or....

python3 /home/zigbee/Downloads/solaredge_modbus-master/example.py --json 192.168.178.22 11502
Traceback (most recent call last):
  File "/home/zigbee/Downloads/solaredge_modbus-master/example.py", line 6, in <module>
    import solaredge_modbus
  File "/usr/local/lib/python3.10/dist-packages/solaredge_modbus/__init__.py", line 7, in <module>
    from pymodbus.client.sync import ModbusTcpClient

Many thanks!!!

Kind regards,

Jasper

**Comment by jvrrr** [comment]
@nmakel 
I think the syntax is wrong, I get a error.

With "pip3  list" I see that I'm running version 0.7.2

Any  other suggestions?

Thanks a lot!!!!

**Comment by jvrrr** [comment]
After some update rounds the sample file is now working, many thanks!!!
