### ISSUE TITLE
Support for Backup Interface

### ISSUE THREAD

**Issue by herbi3** [nmakel/solaredge_modbus#71]
With solaredge BUI, it shows if the system is running on or off grid. It would be great to somehow grab that information.

These are connected via rs485, but I don't believe there's anything modbus related. Do you or anyone have an idea of how to determine if the system is running in on or off grid mode?

This is their install guide, nothing mentioned about modbus etc. nothing shows under modbus section within the inverter either (I was hoping to grab a modbus ID but no luck)
https://964176.app.netsuite.com/core/media/media.nl?id=16354282&c=964176&h=1ff37e5f176af711cf09&_xt=.pdf#page19

**Comment by herbi3** [comment]
thanks @nmakel !

I had to change `from pymodbus.client import ModbusTcpClient` to `from pymodbus.client.sync import ModbusTcpClient`

I have no other connections active to the inverter, but it keeps failing. are there any other recent changes from pymodbus I need to include?

```
Traceback (most recent call last):
  File "./mapse.py", line 33, in <module>
    result = client.read_holding_registers(i, 1, slave=args.unit)
  File "/usr/local/lib/python3.8/dist-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.8/dist-packages/pymodbus/client/sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(10.0.2.3:1502)]
```

**Comment by herbi3** [comment]
thanks @nmakel - here is the output_with_backup

```
40000 21365
40001 28243
40002 1
40003 65
40004 21359
40005 27745
40006 29253
40007 25703
40008 25888
40009 0
40010 0
40011 0
40012 0
40013 0
40014 0
40015 0
40016 0
40017 0
40018 0
40019 0
40020 21317
40021 12592
40022 12336
40023 12360
40024 11585
40025 21843
40026 20034
40027 16984
40028 12596
40029 0
40030 0
40031 0
40032 0
40033 0
40034 0
40035 0
40036 0
40037 0
40055 12850
40056 0
40057 0
40058 0
40059 0
40060 0
40062 0
40063 0
40064 0
40065 0
40066 0
40068 1
40069 101
40070 50
40072 653
40073 65535
40074 65535
40075 65534
40077 65535
40078 65535
40079 2416
40080 65535
40081 65535
40082 65535
40083 15494
40084 65535
40085 49971
40086 65533
40087 15530
40088 65535
40089 10488
40090 65534
40091 9976
40092 65534
40093 2
40094 44594
40095 0
40096 4028
40132 0
40133 0
40134 0
40135 0
40136 0
40137 0
40138 0
40139 21317
40140 11597
40141 21586
40142 11571
40143 22829
40144 13360
40145 12374
40146 11586
40147 0
40148 0
40149 0
40150 0
40151 0
40152 0
40153 0
40154 0
40156 28783
40157 29300
40158 11081
40159 28016
40160 28530
40162 0
40163 14136
40164 0
40165 0
40166 0
40167 0
40168 0
40169 0
40170 0
40171 13872
40172 13881
40173 13620
40174 14388
40175 13568
40177 0
40179 0
40180 0
40181 0
40182 0
40183 0
40184 0
40185 0
40186 0
40187 1
40188 203
40190 39
40191 38
40192 0
40194 65535
40195 23888
40196 23888
40197 23
40198 8
40199 0
40200 0
40201 0
40202 0
40203 65534
40204 4997
40205 65534
40206 913
40207 1009
40208 0
40209 65532
40210 0
40211 1062
40212 1070
40214 18
40215 0
40216 65194
40217 65212
40218 0
40219 65518
40220 0
40221 3753
40222 56796
40223 10000
40224 10000
40225 65534
40260 0
40262 0
40263 0
40265 0
40266 0
40267 0
40268 0
40269 0
40270 0
40271 0
40272 0
40274 0
40275 0
40276 0
40277 0
40278 0
40279 0
40280 0
40281 0
40282 0
40283 0
40284 0
40285 0
40286 0
40287 0
40288 0
40289 0
40290 0
40291 0
40292 32768
40293 0
40294 0
40295 701
40297 0
40298 1
40299 65535
40301 0
40302 0
40303 65535
40304 65535
40305 168
40306 168
40307 10
40308 99
40310 2410
40311 1203
40312 0
40313 49981
40314 65535
40315 65535
40318 65535
40319 65535
40320 65535
40321 65535
40322 65535
40324 65535
40326 65535
40327 65535
40328 65535
40329 65535
40330 32768
40331 32768
40332 32768
40333 32768
40334 32768
40335 32768
40336 32768
40337 32768
40338 32768
40405 65535
40406 65535
40407 65535
40408 0
40409 65535
40410 65533
40411 1
40412 65534
40413 1
40414 1
40415 0
40416 0
40417 0
40418 0
40420 0
40421 0
40422 0
40423 0
40424 0
40426 0
40427 0
40428 0
40429 0
40430 0
40431 0
40505 11000
40506 8913
40507 0
40508 50150
40509 0
40510 47500
40511 0
40512 60
40513 0
40514 0
40515 0
40516 360
40518 65535
40519 65534
40521 704
40522 65
40523 0
40605 0
40607 0
40608 0
40609 12409
40610 0
40611 3500
40612 1
40613 999
40616 4400
40617 9565
40618 0
40620 0
40621 11217
40622 59536
40623 13043
40624 59536
40625 0
40626 0
40627 0
40628 0
40629 0
40630 0
40634 0
40635 0
40636 0
40637 0
40638 0
40639 0
40640 0
40641 0
40642 0
40643 0
40644 0
40645 0
40646 0
40647 706
40648 47
40650 0
40651 1
40652 6
40694 0
40696 707
40697 105
40698 1
40699 0
40700 1
40701 5
40702 2
40703 65534
40705 1
40706 2
40707 3043
40708 0
40709 1800
40756 0
40757 0
40758 0
40759 0
40760 0
40761 0
40762 0
40763 0
40764 0
40765 0
40767 0
40769 0
40770 0
40771 0
40772 0
40773 0
40774 0
40775 0
40776 0
40778 0
40779 0
40780 0
40781 0
40782 0
40783 0
40784 0
40785 0
40786 0
40787 0
40788 0
40789 0
40790 0
40791 0
40792 0
40793 0
40794 0
40795 0
40796 0
40797 0
40798 0
40799 0
40800 0
40801 0
40802 0
40803 708
40804 105
40805 1
40859 0
40860 0
40861 0
40862 0
40863 0
40864 0
40865 0
40866 0
40867 0
40869 0
40870 0
40871 0
40872 0
40873 0
40874 0
40875 0
40876 0
40877 0
40878 0
40879 0
40880 0
40881 0
40882 0
40883 0
40884 0
40885 0
40887 0
40888 0
40889 0
40890 0
40891 0
40892 0
40893 0
40894 0
40895 0
40896 0
40898 0
40899 0
40900 0
40901 0
40902 0
40903 0
40904 0
40905 0
40906 0
40907 0
40908 0
40909 0
40975 0
40976 0
40977 0
40978 0
40979 0
40980 0
40981 0
40982 0
40983 0
40984 0
40986 0
40987 0
40988 0
40989 0
40990 0
40991 0
40992 0
40993 0
40994 0
40995 0
40996 0
40997 0
40998 0
40999 0
41000 0
41001 0
41002 0
41003 0
41004 0
41005 0
41006 0
41007 0
41008 0
41009 0
41010 0
41011 0
41012 0
41013 0
41014 0
41015 0
41016 0
41017 0
41039 0
41040 0
41041 0
41042 0
41043 0
41044 0
41045 0
41046 0
41047 710
41048 135
41051 1
41052 5
41053 2
41054 65534
41056 1
41057 5
41058 0
41059 5200
41060 0
41061 180
41062 0
41064 8
41065 55712
41066 0
41067 10000
41068 8
41069 55712
41070 0
41071 10000
41072 8
41073 55712
41074 0
41075 10000
41076 8
41077 55712
41078 0
41079 0
41080 0
41081 0
41082 0
41083 0
41084 0
41085 0
41086 0
41124 0
41125 0
41126 0
41127 0
41128 0
41129 0
41130 0
41132 0
41133 0
41134 0
41135 0
41136 0
41137 0
41138 0
41139 0
41140 0
41141 0
41142 0
41143 0
41145 0
41186 0
41187 0
41188 1
41189 2
41191 65535
41192 65535
41193 65535
41194 65535
41195 65533
41196 65533
41197 65533
41198 0
41199 30000
41200 0
41201 30000
41202 0
41203 0
41204 0
41205 3500
41206 32768
41207 1
41208 0
41209 0
41210 0
41211 0
41213 0
41214 0
41215 0
41217 0
41218 712
41220 0
41221 0
41222 1
41223 6
41224 2
41225 65535
41226 65535
41227 65535
41228 65535
41229 65535
41230 65534
41231 65534
41232 0
41233 0
41234 65535
41235 1
41236 0
41237 0
41238 2500
41239 0
41240 5000
41241 0
41242 6000
41243 0
41244 7000
41245 0
41246 10000
41247 0
41248 0
41249 0
41250 65535
41251 0
41257 0
41258 0
41259 0
41260 0
41261 0
41262 0
41263 0
41264 713
41265 7
41266 65535
41268 10000
41269 65535
41270 65535
41271 65534
41272 65534
53840 0
53841 0
57600 21359
57632 21325
57665 0
57904 0
57920 255
57921 0
57994 0
57995 0
57996 0
57997 0
57998 0
57999 0
58000 0
58001 0
58002 0
58003 0
58432 255
58433 0
58506 0
58508 0
58509 0
58510 0
58511 0
58512 0
58513 0
58514 0
58515 0
58516 0
58517 0
58518 0
58519 0
58520 0
58521 0
58522 32
59648 28499
59664 17747
59680 19795
59904 0
59936 0
59952 0
59968 255
59969 0
```

and then without backup

```
40000 21365
40001 28243
40002 1
40003 65
40004 21359
40005 27745
40006 29253
40007 25703
40008 25888
40009 0
40010 0
40011 0
40012 0
40014 0
40015 0
40016 0
40017 0
40018 0
40019 0
40020 21317
40021 12592
40022 12336
40023 12360
40024 11585
40027 16984
40028 12596
40029 0
40030 0
40031 0
40032 0
40033 0
40034 0
40035 0
40036 0
40037 0
40038 0
40039 0
40040 0
40041 0
40042 0
40043 0
40045 12340
40046 11824
40047 12337
40048 14126
40049 12336
40050 13366
40051 0
40052 14132
40053 12343
40054 13625
40055 12344
40056 0
40057 0
40058 0
40059 0
40060 0
40061 0
40062 0
40063 0
40064 0
40065 0
40066 0
40067 0
40068 1
40069 101
40070 50
40071 949
40073 65535
40074 65535
40075 65534
40076 2443
40077 65535
40078 65535
40079 2442
40080 65535
40081 65535
40082 65535
40083 18402
40084 65535
40086 65533
40087 23164
40088 65535
40089 51385
40090 65535
40091 57553
40092 65534
40093 2
40094 43830
40095 0
40096 4799
40097 65533
40098 3876
40099 65535
40100 18562
40101 65535
40102 32768
40103 4432
40105 32768
40106 65534
40107 4
40108 0
40109 65535
40110 65535
40111 65535
40112 65535
40113 0
40114 0
40115 65535
40116 65535
40117 65535
40118 65535
40120 0
40121 1
40122 65
40123 21359
40124 27745
40125 29253
40126 25703
40127 25856
40128 0
40129 0
40130 0
40132 0
40133 0
40134 0
40135 0
40136 0
40137 0
40138 0
40139 21317
40140 11597
40142 11571
40143 22829
40144 13360
40145 12374
40146 11586
40147 0
40148 0
40149 0
40150 0
40151 0
40152 0
40153 0
40154 0
40155 17784
40156 28783
40157 29300
40158 11081
40159 28016
40160 28530
40161 29696
40162 0
40163 14136
40164 0
40165 0
40166 0
40167 0
40168 0
40169 0
40170 0
40171 13872
40172 13881
40173 13616
40174 12339
40175 12288
40176 0
40177 0
40178 0
40180 0
40181 0
40182 0
40183 0
40184 0
40185 0
40186 0
40187 1
40188 203
40189 105
40190 87
40196 24390
40197 24
40198 9
40199 0
40200 0
40201 0
40202 0
40203 65534
40204 5002
40205 65534
40206 1618
40207 1622
40209 65535
40210 0
40211 2131
40212 2122
40214 13
40215 0
40216 1376
40217 1361
40218 1
40219 13
40220 0
40222 57946
40224 10000
40225 65534
40226 2
40227 16397
40228 2
40229 16484
40230 0
40231 0
40232 0
40233 0
40234 0
40235 16873
40236 0
40237 16714
40238 0
40239 0
40240 0
40241 283
40242 0
40243 0
40244 0
40245 0
40246 0
40247 0
40248 0
40249 0
40250 0
40251 0
40252 0
40253 0
40254 0
40255 0
40256 0
40257 0
40258 0
40259 32768
40260 0
40265 0
40266 0
40267 0
40268 0
40269 0
40270 0
40271 0
40272 0
40273 0
40274 0
40275 0
40276 0
40277 0
40278 0
40279 0
40280 0
40281 0
40282 0
40283 0
40284 0
40285 0
40286 0
40287 0
40288 0
40289 0
40290 0
40291 0
40294 0
40295 701
40296 153
40297 0
40298 1
40300 1
40301 0
40302 0
40303 65535
40304 65535
40305 188
40306 231
40307 65403
40308 81
40309 32768
40310 2441
40311 1220
40312 0
40313 50008
40314 65535
40315 65535
40316 65535
40317 65535
40318 65535
40319 65535
40320 65535
40321 65535
40322 65535
40323 65535
40324 65535
40325 65535
40326 65535
40327 65535
40329 65535
40330 32768
40331 32768
40332 32768
40333 32768
40334 32768
40335 32768
40336 32768
40337 32768
40338 32768
40339 65535
40340 65535
40341 65535
40342 2441
40343 65535
40344 65535
40345 65535
40346 65535
40347 65535
40348 65535
40349 65535
40350 65535
40351 65535
40352 65535
40353 65535
40358 65535
40359 32768
40360 32768
40361 32768
40362 65535
40363 65535
40364 65535
40365 0
40366 65535
40367 65535
40368 65535
40369 65535
40370 65535
40371 65535
40372 65535
40373 65535
40374 65535
40375 65535
40376 65535
40377 65535
40378 65535
40379 65535
40380 65535
40381 65535
40382 32768
40383 32768
40384 32768
40385 65535
40386 65535
40387 65535
40388 0
40389 65535
40390 65535
40391 65535
40392 65535
40393 65535
40394 65535
40395 65535
40396 65535
40397 65535
40398 65535
40399 65535
40400 65535
40401 65535
40402 65535
40403 65535
40404 65535
40405 65535
40406 65535
40407 65535
40408 0
40409 65535
40410 65533
40411 1
40412 65534
40413 1
40414 1
40415 0
40416 0
40418 0
40419 0
40420 0
40421 0
40422 0
40423 0
40424 0
40425 0
40426 0
40427 0
40428 0
40429 0
40430 0
40431 0
40432 0
40433 0
40434 0
40435 0
40436 0
40437 0
40438 0
40440 0
40441 0
40442 0
40443 0
40444 0
40445 0
40446 0
40447 0
40448 0
40449 0
40450 702
40451 50
40452 10000
40453 8000
40454 80
40455 8000
40456 80
40457 10000
40458 6000
40459 6000
40460 5400
40461 65535
40462 5400
40463 65535
40464 2300
40465 2530
40466 2023
40467 65535
40468 65535
40469 65535
40470 0
40471 1
40472 2
40473 65535
40474 63487
40475 65535
40476 65535
40477 65535
40478 65535
40479 65535
40480 65535
40481 65535
40482 65535
40483 65535
40484 65535
40485 65535
40486 65535
40487 65535
40488 65535
40489 65535
40490 65535
40491 65535
40492 65535
40493 65535
40494 65535
40495 0
40496 65534
40497 0
40498 0
40499 65535
40500 0
40501 0
40502 703
40503 17
40504 1
40505 11000
40506 8913
40507 0
40508 50150
40509 0
40510 47500
40511 0
40512 60
40513 0
40514 0
40515 0
40516 360
40517 65535
40518 65535
40519 65534
40520 65533
40521 704
40522 65
40523 0
40524 65535
40525 65535
40526 65535
40527 65535
40528 65535
40529 65535
40530 65535
40531 65535
40532 65535
40533 65535
40534 65535
40535 0
40536 65535
40537 65535
40538 65535
40539 65535
40540 65535
40541 65535
40542 65535
40543 0
40544 0
40545 65535
40546 65535
40551 65535
40552 65535
40553 65535
40554 65535
40555 65535
40556 0
40557 0
40558 65535
40559 0
40560 0
40561 32768
40562 0
40563 0
40564 32768
40565 65535
40566 65535
40567 65535
40568 65535
40569 65535
40570 65535
40571 65535
40572 65535
40573 65535
40574 65533
40575 65534
40576 0
40577 65534
40578 0
40579 65534
40580 1000
40581 0
40582 65535
40583 65535
40584 65535
40585 65535
40587 65535
40588 705
40589 57
40590 1
40591 0
40592 1
40593 6
40594 2
40595 65535
40599 65535
40600 65534
40601 65534
40602 65533
40603 6
40604 0
40605 0
40606 100
40607 0
40608 0
40609 49498
40611 3500
40612 1
40613 1000
40614 4400
40615 9000
40616 4400
40617 9565
40618 0
40619 10434
40620 0
40622 59536
40623 13043
40624 59536
40625 0
40626 0
40628 0
40629 0
40630 0
40631 0
40632 0
40633 0
40634 0
40635 0
40636 0
40637 0
40638 0
40639 0
40640 0
40641 0
40642 0
40644 0
40645 0
40646 0
40647 706
40648 47
40649 0
40650 0
40651 1
40652 6
40653 2
40654 65535
40655 65535
40656 65535
40657 65535
40658 65535
40659 65534
40660 0
40661 65533
40662 6
40663 0
40664 0
40669 9000
40670 100
40671 9565
40672 100
40673 11000
40674 100
40675 11304
40676 15
40677 12000
40678 15
40679 0
40680 0
40681 0
40682 0
40683 0
40684 0
40685 0
40686 0
40687 0
40688 0
40689 0
40690 0
40691 0
40692 0
40693 0
40694 0
40695 0
40696 707
40697 105
40698 1
40699 0
40700 1
40701 5
40702 2
40703 65534
40704 65533
40705 1
40706 2
40707 3043
40708 0
40709 1800
40710 7826
40711 0
40712 10800
40713 0
40716 0
40717 8
40718 55712
40719 0
40720 8
40721 55712
40722 0
40723 0
40724 0
40725 0
40726 0
40727 0
40728 0
40729 0
40731 0
40732 0
40733 0
40734 0
40735 0
40736 0
40737 0
40738 0
40739 0
40740 0
40741 0
40742 0
40743 0
40744 0
40745 0
40746 0
40747 0
40748 0
40749 0
40750 0
40751 0
40752 0
40753 0
40754 0
40755 0
40756 0
40757 0
40758 0
40760 0
40761 0
40762 0
40763 0
40764 0
40765 0
40766 0
40767 0
40769 0
40770 0
40771 0
40772 0
40773 0
40774 0
40775 0
40776 0
40777 0
40778 0
40779 0
40780 0
40781 0
40782 0
40783 0
40784 0
40785 0
40786 0
40787 0
40788 0
40789 0
40790 0
40791 0
40792 0
40793 0
40794 0
40795 0
40796 0
40797 0
40798 0
40799 0
40800 0
40801 0
40802 0
40803 708
40804 105
40805 1
40807 1
40809 2
40810 65534
40811 65533
40812 1
40813 5
40814 11956
40815 0
40816 180
40817 11521
40818 0
40819 1800
40820 17391
40821 8
40822 55712
40823 17391
40825 55712
40826 11217
40827 9
40828 10176
40829 0
40830 0
40831 0
40832 0
40833 0
40834 0
40835 0
40836 0
40837 0
40838 0
40839 0
40840 0
40841 0
40842 0
40843 0
40844 0
40845 0
40846 0
40847 0
40848 0
40849 0
40850 0
40851 0
40852 0
40853 0
40854 0
40855 0
40856 0
40857 0
40858 0
40859 0
40860 0
40861 0
40862 0
40863 0
40864 0
40865 0
40866 0
40867 0
40868 0
40869 0
40870 0
40871 0
40872 0
40873 0
40874 0
40875 0
40876 0
40877 0
40878 0
40879 0
40880 0
40881 0
40883 0
40884 0
40887 0
40888 0
40889 0
40890 0
40891 0
40892 0
40893 0
40894 0
40895 0
40896 0
40897 0
40898 0
40899 0
40900 0
40901 0
40903 0
40904 0
40905 0
40906 0
40907 0
40908 0
40909 0
40910 709
40911 135
40912 1
40913 0
40914 1
40915 5
40916 2
40917 65534
40918 65533
40919 1
40920 2
40921 0
40922 4700
40923 0
40924 1800
40925 0
40926 0
40927 8
40928 55712
40929 0
40930 2000
40931 8
40932 55712
40933 0
40934 2000
40935 8
40936 55712
40937 0
40938 2000
40939 8
40940 55712
40941 0
40942 0
40943 0
40944 0
40945 0
40946 0
40947 0
40948 0
40949 0
40950 0
40951 0
40952 0
40953 0
40954 0
40955 0
40956 0
40957 0
40958 0
40959 0
40960 0
40961 0
40962 0
40964 0
40965 0
40966 0
40967 0
40968 0
40969 0
40970 0
40971 0
40972 0
40973 0
40974 0
40975 0
40976 0
40977 0
40978 0
40979 0
40980 0
40981 0
40982 0
40983 0
40984 0
40985 0
40988 0
40989 0
40991 0
40992 0
40993 0
40994 0
40995 0
40996 0
40997 0
40998 0
40999 0
41000 0
41001 0
41002 0
41003 0
41004 0
41005 0
41006 0
41007 0
41008 0
41009 0
41010 0
41011 0
41012 0
41013 0
41014 0
41015 0
41016 0
41017 0
41018 0
41019 0
41020 0
41021 0
41022 0
41023 0
41024 0
41025 0
41026 0
41027 0
41028 0
41029 0
41030 0
41031 0
41032 0
41033 0
41034 0
41035 0
41036 0
41037 0
41038 0
41039 0
41040 0
41041 0
41042 0
41043 0
41044 0
41045 0
41046 0
41047 710
41048 135
41049 1
41050 0
41051 1
41052 5
41053 2
41054 65534
41055 65533
41056 1
41057 5
41058 0
41059 5200
41060 0
41061 180
41062 0
41063 10000
41064 8
41065 55712
41066 0
41067 10000
41068 8
41069 55712
41070 0
41071 10000
41072 8
41073 55712
41074 0
41075 10000
41076 8
41081 0
41082 0
41083 0
41084 0
41085 0
41086 0
41087 0
41088 0
41089 0
41090 0
41091 0
41092 0
41093 0
41094 0
41095 0
41096 0
41097 0
41098 0
41099 0
41100 0
41101 0
41102 0
41103 0
41104 0
41105 0
41106 0
41107 0
41108 0
41109 0
41110 0
41111 0
41112 0
41113 0
41114 0
41115 0
41116 0
41117 0
41118 0
41119 0
41120 0
41121 0
41122 0
41123 0
41124 0
41125 0
41127 0
41128 0
41129 0
41130 0
41131 0
41132 0
41133 0
41134 0
41135 0
41136 0
41137 0
41138 0
41139 0
41140 0
41141 0
41142 0
41143 0
41144 0
41145 0
41146 0
41147 0
41148 0
41149 0
41151 0
41152 0
41153 0
41154 0
41155 0
41157 0
41158 0
41159 0
41160 0
41161 0
41162 0
41164 0
41165 0
41166 0
41167 0
41168 0
41169 0
41170 0
41171 0
41172 0
41173 0
41174 0
41175 0
41176 0
41177 0
41178 0
41179 0
41180 0
41181 0
41182 0
41183 0
41184 711
41185 32
41186 0
41187 0
41188 1
41189 2
41190 65535
41191 65535
41192 65535
41193 65535
41194 65535
41195 65533
41196 65533
41197 65533
41198 0
41199 30000
41200 0
41201 30000
41202 0
41203 0
41204 0
41206 32768
41207 1
41208 0
41209 0
41210 0
41211 0
41212 0
41213 0
41214 0
41215 0
41216 32768
41217 0
41218 712
41219 44
41220 1
41221 0
41222 1
41223 6
41224 2
41225 65535
41226 65535
41227 65535
41228 65535
41229 65535
41230 65534
41231 65534
41232 0
41233 0
41234 65535
41235 1
41236 0
41237 0
41238 2500
41239 0
41240 5000
41241 0
41242 6000
41243 0
41244 7000
41245 0
41246 10000
41247 0
41248 0
41249 0
41250 65535
41251 0
41252 0
41253 0
41254 0
41255 0
41259 0
41260 0
41261 0
41262 0
41263 0
41264 713
41265 7
41266 65535
41268 0
41269 65535
41270 65535
41271 65534
41274 0
53840 0
53841 0
54356 0
56404 0
57344 1
57345 0
57346 16384
57347 17820
57348 0
57349 1
57350 0
57351 0
57352 0
57353 0
57354 0
57355 3600
57356 0
57357 65535
57358 49152
57359 17832
57360 49152
57361 17832
57362 0
57363 0
57364 3
57365 65535
57366 65407
57367 0
57368 0
57370 0
57371 1
57372 0
57373 0
57374 0
57375 0
57376 1
57377 15
57378 16384
57379 17820
57380 65535
57381 65535
57382 65535
57383 0
57384 0
57388 0
57392 65407
57393 0
57394 0
57395 0
57396 0
57397 0
57398 0
57616 0
57632 0
57648 0
57664 255
57665 0
57738 0
57739 0
57740 0
57741 0
57742 0
57743 0
57744 0
57745 0
57746 0
57747 0
57748 0
57749 0
57750 0
57751 0
57752 0
57753 0
57754 0
57872 0
57888 0
57904 0
57920 255
57921 0
57994 0
57995 0
57996 0
57997 0
57998 0
57999 0
58000 0
58001 0
58003 0
58004 0
58006 0
58007 0
58008 0
58009 0
58010 0
58112 0
58113 0
58114 407
58115 415
58116 393
58117 429
58118 7000
58119 7000
58120 1
58121 411
58368 0
58384 0
58400 0
58416 0
58432 255
58433 0
58506 0
58507 0
58508 0
58509 0
58510 0
58511 0
58512 0
58513 0
58514 0
58515 0
58516 0
58517 0
58518 0
58519 0
58520 0
58521 0
58522 0
59392 1
59393 0
59394 17820
59395 16384
59396 0
59398 0
59399 0
59400 0
59401 0
59402 0
59403 0
59404 3600
59405 65535
59406 17832
59407 49152
59408 17832
59409 49152
59410 0
59411 0
59412 3
59413 65407
59414 65535
59415 0
59418 0
59419 1
59420 0
59421 0
59422 0
59424 1
59425 15
59426 17820
59427 16384
59428 65535
59429 65535
59430 65535
59431 0
59432 0
59433 17427
59434 31487
59435 0
59436 0
59437 17428
59438 54771
59439 65407
59440 65535
59441 0
59442 0
59443 0
59444 0
59445 0
59446 0
59648 0
59664 0
59680 0
59696 0
59712 255
59786 0
59787 0
59788 0
59789 0
59790 0
59791 0
59792 0
59793 0
59794 0
59795 0
59796 0
59797 0
59798 0
59799 0
59800 0
59801 0
59802 0
59904 0
59920 0
59936 0
59952 0
59968 255
```

**Comment by Ruebenschus** [comment]
Hi there,
I have a new hybrid inverter with backup box, too. I think my backup box is newer than the one mentioned in the thread. It has a little different form factor. It's called SolarEdge Home Backup-Interface. I also have two batteries installed, plus one meter at the main network inlet and one within the Backup-Interface. 

solaredge_modbus does only see the smart meter and the batteries, but not the Backup-Interface with builtin meter. 
Is there anything I can provide to help you skilled guys to include those devices?

Cheers,
 Joachim

The mapse.py sais "Failed to connect" whereas example.py shows (in the case of not-backup operation):

`{
    "c_id": "SunS",
    "c_did": 1,
    "c_length": 65,
    "c_manufacturer": "SolarEdge",
    "c_model": "SE10K-RWB48BFN4",
    "c_version": "0004.0017.0136",
    "c_serialnumber": "..........",
    "c_deviceaddress": 1,
    "c_sunspec_did": 103,
    "c_sunspec_length": 50,
    "current": 178,
    "l1_current": 54,
    "l2_current": 65,
    "l3_current": 57,
    "current_scale": -2,
    "l1_voltage": 4019,
    "l2_voltage": 4008,
    "l3_voltage": 4028,
    "l1n_voltage": 2323,
    "l2n_voltage": 2317,
    "l3n_voltage": 2320,
    "voltage_scale": -1,
    "power_ac": 3833,
    "power_ac_scale": -1,
    "frequency": 4998,
    "frequency_scale": -2,
    "power_apparent": 4129,
    "power_apparent_scale": -1,
    "power_reactive": -15348,
    "power_reactive_scale": -2,
    "power_factor": -9271,
    "power_factor_scale": -2,
    "energy_total": 10944,
    "energy_total_scale": 0,
    "current_dc": 4742,
    "current_dc_scale": -4,
    "voltage_dc": 8204,
    "voltage_dc_scale": -1,
    "power_dc": 3891,
    "power_dc_scale": -1,
    "temperature": 3794,
    "temperature_scale": -2,
    "status": 4,
    "vendor_status": 0,
    "rrcr_state": 0,
    "active_power_limit": 100,
    "cosphi": 0,
    "commit_power_control_settings": 0,
    "restore_power_control_default_settings": 0,
    "reactive_power_config": 0,
    "reactive_power_response_time": 200,
    "advanced_power_control_enable": 1,
    "export_control_mode": 0,
    "export_control_limit_mode": 0,
    "export_control_site_limit": 0,
    "meters": {
        "Meter1": {
            "c_manufacturer": "SolarEdge",
            "c_model": "MTR-240-3PC1-D-A-MW",
            "c_option": "Export+Import",
            "c_version": "1.0.34",
            "c_serialnumber": "1677875835",
            "c_deviceaddress": 3,
            "c_sunspec_did": 203,
            "c_sunspec_length": 105,
            "current": 24,
            "l1_current": 9,
            "l2_current": 8,
            "l3_current": 6,
            "current_scale": -1,
            "voltage_ln": 23234,
            "l1n_voltage": 23234,
            "l2n_voltage": 23115,
            "l3n_voltage": 23186,
            "voltage_ll": 0,
            "l12_voltage": 0,
            "l23_voltage": 0,
            "l31_voltage": 0,
            "voltage_scale": -2,
            "frequency": 4999,
            "frequency_scale": -2,
            "power": 1,
            "l1_power": -110,
            "l2_power": 54,
            "l3_power": 56,
            "power_scale": 0,
            "power_apparent": 347,
            "l1_power_apparent": 159,
            "l2_power_apparent": 149,
            "l3_power_apparent": 108,
            "power_apparent_scale": 0,
            "power_reactive": -347,
            "l1_power_reactive": -115,
            "l2_power_reactive": -138,
            "l3_power_reactive": -92,
            "power_reactive_scale": 0,
            "power_factor": -419,
            "l1_power_factor": 4650,
            "l2_power_factor": -2599,
            "l3_power_factor": -3310,
            "power_factor_scale": -2,
            "export_energy_active": 1371,
            "l1_export_energy_active": 809,
            "l2_export_energy_active": 1433,
            "l3_export_energy_active": 1654,
            "import_energy_active": 992722,
            "l1_import_energy_active": 137564,
            "l2_import_energy_active": 493779,
            "l3_import_energy_active": 363904,
            "energy_active_scale": 0,
            "export_energy_apparent": 0,
            "l1_export_energy_apparent": 0,
            "l2_export_energy_apparent": 0,
            "l3_export_energy_apparent": 0,
            "import_energy_apparent": 0,
            "l1_import_energy_apparent": 0,
            "l2_import_energy_apparent": 0,
            "l3_import_energy_apparent": 0,
            "energy_apparent_scale": -32768,
            "import_energy_reactive_q1": 0,
            "l1_import_energy_reactive_q1": 0,
            "l2_import_energy_reactive_q1": 0,
            "l3_import_energy_reactive_q1": 0,
            "import_energy_reactive_q2": 0,
            "l1_import_energy_reactive_q2": 0,
            "l2_import_energy_reactive_q2": 0,
            "l3_import_energy_reactive_q2": 0,
            "export_energy_reactive_q3": 0,
            "l1_export_energy_reactive_q3": 0,
            "l2_export_energy_reactive_q3": 0,
            "l3_export_energy_reactive_q3": 0,
            "export_energy_reactive_q4": 0,
            "l1_export_energy_reactive_q4": 0,
            "l2_export_energy_reactive_q4": 0,
            "l3_export_energy_reactive_q4": 0,
            "energy_reactive_scale": -32768
        }
    },
    "batteries": {
        "Battery1": {
            "c_manufacturer": "SolarEdge",
            "c_model": "SolarEdge Home Battery 9.2kWh",
            "c_version": "48V DCDC 3.1.16 BMS 1.1300.0",
            "c_serialnumber": "7B0737E4",
            "c_deviceaddress": 112,
            "c_sunspec_did": 0,
            "rated_energy": 9200.0,
            "maximum_charge_continuous_power": 5650.0,
            "maximum_discharge_continuous_power": 8192.0,
            "maximum_charge_peak_power": 5150.0,
            "maximum_discharge_peak_power": 8600.0,
            "average_temperature": 18.30000114440918,
            "maximum_temperature": 0.0,
            "instantaneous_voltage": 819.8668823242188,
            "instantaneous_current": -1.5764518976211548,
            "instantaneous_power": 1290.0,
            "lifetime_export_energy_counter": 82,
            "lifetime_import_energy_counter": 3081,
            "maximum_energy": 9200.0,
            "available_energy": 8280.0,
            "soh": 100.0,
            "soe": 42.22222137451172,
            "status": 3,
            "status_internal": 3,
            "event_log": 0,
            "event_log_internal": 0
        }
    }
}
`
